services:    
  cache:
    image: redis

  db:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - main-network
    ports:
      - "5435:5432"
   
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    env_file:
      - .env
    ports:
      - "5050:80"
    restart: always
    depends_on:
      - db
    networks:
      - main-network
  migrations:
    build: .
    volumes:
      - .:/app
    command: sh -c "alembic upgrade head"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    networks:
      - main-network
    
  app:
    build: .
    volumes:
      - .:/app
    command: [ "uvicorn", "src.main:app", "--reload", "--host", "0.0.0.0", "--port", "8000" ]
    env_file:
      - .env
    depends_on:
      - migrations
      - db
      - cache
    networks:
      - main-network

volumes:
  pg-data:
  
networks:
  main-network: